### ISSUE TITLE
Require onnxruntime-gpu instead of onnxruntime

### ISSUE THREAD

**Issue by wfjsw** [pythongosssss/ComfyUI-WD14-Tagger#23]
It seems installing `onnxruntime` on top of `onnxruntime-gpu` will strip the ability of ONNX runtime to use CUDA.

**Comment by la-darknesss** [comment]
I'm not sure if it's related.
Is the error message something like the following?
```
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:456 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
```

The current version of onnxruntime is 1.17.0, but it seems that an error is occurring.
Please try downgrading to version 1.16.3 with the following commands:
```
python -m pip install onnxruntime==1.16.3
python -m pip install onnxruntime-gpu==1.16.3
```

**Comment by wfjsw** [comment]
No. 
If you install `onnxruntime-gpu` first and then `onnxruntime`, you will notice that only `CPUExecutionProvider` is available.

**Comment by 52Hz-p** [comment]
您好，请问您解决了吗

**Comment by VitaliyAT** [comment]
Not clear how solve this problem. Lot of teoretical minds instad step-by-step how-to-do higher. I am especially gifted - I don't undersdtand it.
4090+7950X
```

> D:\Ai\SD\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
> ** ComfyUI start up time: 2024-05-20 13:03:17.800563
> 
> Prestartup times for custom nodes:
>    0.0 seconds: D:\Ai\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
>    0.0 seconds: D:\Ai\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
> 
> Total VRAM 23028 MB, total RAM 97432 MB
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
> VAE dtype: torch.bfloat16
> Using pytorch cross attention
> Using pytorch cross attention
> Traceback (most recent call last):
>   File "D:\Ai\SD\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1879, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "D:\Ai\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\__init__.py", line 2, in <module>
>     from .animatediff.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
>   File "D:\Ai\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\nodes.py", line 22, in <module>
>     from .sampling import animatediff_sample_factory
>   File "D:\Ai\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 9, in <module>
>     from comfy.samplers import lcm
> ImportError: cannot import name 'lcm' from 'comfy.samplers' (D:\Ai\SD\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py)
> 
> Cannot import D:\Ai\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved module for custom nodes: cannot import name 'lcm' from 'comfy.samplers' (D:\Ai\SD\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py)
> [Crystools INFO] Crystools version: 1.12.0
> [Crystools INFO] CPU: AMD Ryzen 9 7950X 16-Core Processor - Arch: AMD64 - OS: Windows 10
> [Crystools INFO] GPU/s:
> [Crystools INFO] 0) NVIDIA GeForce RTX 4090
> [Crystools INFO] NVIDIA Driver: 551.76
> ### Loading: ComfyUI-Impact-Pack (V4.27.4)
> e: module 'sys' has no attribute '__comfyui_manager_register_message_collapse'
> ### Loading: ComfyUI-Impact-Pack (Subpack: V0.3)
> ### Loading: ComfyUI-Inspire-Pack (V0.32.4)
> ### Loading: ComfyUI-Manager (V0.34)
> ### ComfyUI Revision: 2194 [11a2ad51] | Released on '2024-05-19'
> ------------------------------------------
> ### N-Suite Revision: dbeb9ae9
> Current version of packaging: 23.2
> Version of cpuinfo: Not found
> Current version of git: 3.1.37
> Current version of moviepy: 1.0.3
> Current version of cv2: 4.8.1
> Current version of skbuild: 0.17.6
> Version of typing: Not found
> Current version of diskcache: 5.6.3
> Current version of llama_cpp: 0.2.26+cu118
> Current version of timm: 0.9.12
> [ReActor] - STATUS - Running v0.5.0-b3 in ComfyUI
> Torch version: 2.1.0+cu118
> Comfyroll Custom Nodes: Loaded
> Registered sys.path: ['D:\\Ai\\SD\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\__init__.py', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_pycocotools', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_oneformer', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_mmpkg', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_midas_repo', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_detectron2', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\controlnet_aux', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_Comfyroll_CustomNodes\\comfy', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_Comfyroll_CustomNodes\\comfy', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Crystools\\nodes\\comfy', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\python_embeded\\lib\\site-packages\\git\\ext\\gitdb', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\ComfyUI\\comfy', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\ComfyUI', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\python_embeded\\python310.zip', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\python_embeded', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\python_embeded\\lib\\site-packages', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\python_embeded\\lib\\site-packages\\win32', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\python_embeded\\lib\\site-packages\\win32\\lib', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\python_embeded\\lib\\site-packages\\Pythonwin', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\modules', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\impact_subpack', '../..', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-N-Nodes\\libs\\rifle', 'D:\\Ai\\SD\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-N-Nodes\\libs']
> DWPose: Onnxruntime with acceleration providers detected. Caching sessions (might take around half a minute)...
> 2024-05-20 13:03:24.8707291 [E:onnxruntime:Default, provider_bridge_ort.cc:1534 onnxruntime::TryGetProviderInfo_TensorRT] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\Ai\SD\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
> 
> *************** EP Error ***************
> EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:456 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
>  when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
> Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
> ****************************************
> 2024-05-20 13:03:25.0982619 [E:onnxruntime:Default, provider_bridge_ort.cc:1534 onnxruntime::TryGetProviderInfo_TensorRT] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\Ai\SD\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
> 
> *************** EP Error ***************
> EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:456 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
>  when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
> Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
> ****************************************

```

**Comment by water110** [comment]
> Hi! Same problem. The generation goes on, the caption appears and I don't understand how much this error affects. Apparently the computation doesn't run on the GPU.
> 
> 4090 + CUDA 12.4, cuDNN 9.0.0 (CUDA 11.8 is also installed on the system and there is CUDA_PATH_V11_8)
> 
> ```
> 2024-03-11 13:40:06.5955372 [E:onnxruntime:Default, provider_bridge_ort.cc:1534 onnxruntime::TryGetProviderInfo_TensorRT] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\ComfyUI\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
> 
> *************** EP Error ***************
> EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:456 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
>  when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
> Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
> ****************************************
> ```
> 
> 1. So... How do I solve this?
> 2. If the generation goes on, it does not affect the quality of the caption? (I have a powerful CPU, generation time is ok even with an error)
> 3. Does the WD14-Tagger support working with CUDA 12?
> 4. Hmmm where is "D:\a_work\1\s\onnxruntime..." coming from? My ComfyUI is on D: but OS on the disk C:
> 5. I don't know why it says `FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\ComfyUI\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"` I checked and this library is really there.

onnxruntime_providers_tensorrt.dll，Where can I download this file

**Comment by yxlwfds** [comment]
me too

onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page

**Comment by phantomwork** [comment]
You can fix this error simply by installing tensorrt:
The below image is the compatibility matrix for the cuda version.
![image](https://github.com/user-attachments/assets/0cd2e272-ec21-4efc-bc7f-f651678aafb5)


This is my environment:
OS: Windows 10
CUDA: 11.8 (Since tensorflow isn't be upgraded from the 2.10 on windows I'm using 11.8)

On Windows OS, tensorrt==8.6 is not supported so you have to install tensorrt-cu11 binary.

> pip install onnxruntime-gpu==1.16.0
> pip install tensorrt-cu11

**Comment by phantomwork** [comment]
> commented

ok
