### ISSUE TITLE
The node does not load

### ISSUE THREAD

**Issue by rrouk** [pythongosssss/ComfyUI-WD14-Tagger#25]
![21323](https://github.com/pythongosssss/ComfyUI-WD14-Tagger/assets/11753091/ab5befbe-101a-4965-b216-4e6a18faf73f)

Greetings. The node does not load, there are no errors according to the logs. I tried to install both through the manager and manually via Git. I even created a folder with models inside and renamed it as was said. I installed the dependencies. Can you tell me what it could be?

**Comment by rrouk** [comment]
E:\ComfyUI>.\python_embeded\python.exe  -s ComfyUI\main.py --windows-standalone-build --listen
** ComfyUI startup time: 2024-02-08 03:54:50.333827
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: E:\ComfyUI\python_embeded\python.exe
** Log path: E:\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.1 seconds: E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12281 MB, total RAM 32684 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Impact-Pack (V4.74)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
### Loading: ComfyUI-Manager (V2.7.1)
[Impact Pack] Wildcards loading done.
### ComfyUI Revision: 1960 [7daad468] | Released on '2024-02-06'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.jsonTraceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\__init__.py", line 3, in <module>
    if init(check_imports=["onnxruntime"]):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\pysssss.py", line 119, in init
    install_js()
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\pysssss.py", line 105, in install_js
    shutil.copytree(src_dir, dst_dir, dirs_exist_ok=True)
  File "shutil.py", line 561, in copytree
  File "shutil.py", line 459, in _copytree
  File "<frozen os>", line 225, in makedirs
FileExistsError: [WinError 183] Невозможно создать файл, так как он уже существует: 'E:\\ComfyUI\\ComfyUI\\web\\extensions\\pysssss/WD14Tagger'


Cannot import E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger module for custom nodes: [WinError 183] Невозможно создать файл, так как он уже существует: 'E:\\ComfyUI\\ComfyUI\\web\\extensions\\pysssss/WD14Tagger'
Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger — копия\__init__.py", line 3, in <module>
    if init(check_imports=["onnxruntime"]):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger — копия\pysssss.py", line 119, in init
    install_js()
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger — копия\pysssss.py", line 105, in install_js
    shutil.copytree(src_dir, dst_dir, dirs_exist_ok=True)
  File "shutil.py", line 561, in copytree
  File "shutil.py", line 459, in _copytree
  File "<frozen os>", line 225, in makedirs
FileExistsError: [WinError 183] Невозможно создать файл, так как он уже существует: 'E:\\ComfyUI\\ComfyUI\\web\\extensions\\pysssss/WD14Tagger'

Cannot import E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger — копия module for custom nodes: [WinError 183] Невозможно создать файл, так как он уже существует: 'E:\\ComfyUI\\ComfyUI\\web\\extensions\\pysssss/WD14Tagger'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: E:\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
E:\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `E:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 211 nodes successfully.

        "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work." - Steve Jobs

**Comment by rrouk** [comment]
oh, I'm sorry. I'm a fool myself. I transferred the folder with the neuron from one computer to another and along this path the pointer to the old location remained. I corrected it and everything is ok. Sorry again!!
E:\ComfyUI\ComfyUI\web\extensions\pysssss
