### ISSUE TITLE
TypeError: 'list' object is not an iterator

### ISSUE THREAD

**Issue by kieteay** [pythongosssss/ComfyUI-WD14-Tagger#37]
右键单击图片选择“WD14 Tagger”时，出错了。
![image](https://github.com/pythongosssss/ComfyUI-WD14-Tagger/assets/13519807/cfc46a8f-41ec-4fd8-80d4-6452ba2fa6b3)

错误信息，如下：
```
TypeError: 'list' object is not an iterator
Error handling request
Traceback (most recent call last):
  File "E:\AI\ComfyUI_portable\python_comfyenv\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_portable\python_comfyenv\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_portable\python_comfyenv\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_portable\ComfyUI\server.py", line 41, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\wd14tagger.py", line 152, in get_tags
    model = next(models, defaults["model"])
```

临时解决方案：

把`ComfyUI-WD14-Tagger\wd14tagger.py`的`第151行`和`第152行`
```py
models = get_installed_models()
model = next(models, defaults["model"])
```
改为
```py
model = defaults["model"]
```

**Comment by EvgeneKuklin** [comment]
Same problem, presumably - after update
My env:
<details>
absl-py                   2.0.0
accelerate                0.25.0
addict                    2.4.0
aiohttp                   3.9.3
aiosignal                 1.3.1
albumentations            1.3.1
annotated-types           0.6.0
antlr4-python3-runtime    4.9.3
anyio                     4.2.0
async-timeout             4.0.3
attrs                     23.1.0
basicsr                   1.4.2
boltons                   23.0.0
cachetools                5.3.3
certifi                   2023.7.22
cffi                      1.16.0
chardet                   5.2.0
charset-normalizer        3.2.0
clip-interrogator         0.6.0
cmake                     3.27.5
colorama                  0.4.6
coloredlogs               15.0.1
colorlog                  6.8.0
colour-science            0.4.4
contourpy                 1.1.1
cssselect2                0.7.0
cstr                      0.1.0
cycler                    0.11.0
dataclasses-json          0.6.4
Deprecated                1.2.14
diffusers                 0.27.2
diskcache                 5.6.3
distro                    1.8.0
einops                    0.7.0
embreex                   2.17.7.post4
evalidate                 2.0.2
exceptiongroup            1.1.3
executing                 2.0.1
fairscale                 0.4.13
ffmpy                     0.3.0
filelock                  3.12.2
flatbuffers               23.5.26
fonttools                 4.42.1
frozenlist                1.4.0
fsspec                    2023.6.0
ftfy                      6.1.1
future                    1.0.0
fvcore                    0.1.5.post20221221
gitdb                     4.0.10
GitPython                 3.1.36
grpcio                    1.62.0
h11                       0.14.0
httpcore                  1.0.2
httpx                     0.26.0
huggingface-hub           0.22.0
humanfriendly             10.0
idna                      3.4
imageio                   2.31.3
imageio-ffmpeg            0.4.9
img2texture               1.0.6
importlib-metadata        6.8.0
iopath                    0.1.10
jaxtyping                 0.2.28
Jinja2                    3.1.2
joblib                    1.3.2
jsonschema                4.20.0
jsonschema-specifications 2023.12.1
kiui                      0.2.6
kiwisolver                1.4.5
kornia                    0.7.2
kornia_rs                 0.1.2
lazy_loader               0.3
lightning-utilities       0.9.0
llama_cpp_python          0.2.6
llvmlite                  0.41.0
lmdb                      1.4.1
lxml                      4.9.3
mapbox-earcut             1.0.1
Markdown                  3.5.2
markdown-it-py            3.0.0
MarkupSafe                2.1.3
marshmallow               3.21.1
matplotlib                3.8.0
matrix-client             0.4.0
mdurl                     0.1.2
mediapipe                 0.10.5
mpmath                    1.3.0
msvc-runtime              14.34.31931
multidict                 6.0.4
mypy-extensions           1.0.0
nerfacc                   0.5.3
networkx                  3.1
ninja                     1.11.1.1
numba                     0.58.0
numexpr                   2.8.7
numpy                     1.23.5
objprint                  0.2.3
omegaconf                 2.3.0
onnx                      1.14.1
onnxruntime               1.16.0
open-clip-torch           2.23.0
openai                    1.6.1
opencv-contrib-python     4.8.0.76
opencv-python             4.8.0.76
opencv-python-headless    4.7.0.72
packaging                 23.1
pandas                    2.1.0
pathspec                  0.11.2
piexif                    1.1.3
pilgram                   1.2.1
pillow                    10.2.0
pip                       23.2.1
platformdirs              3.10.0
plyfile                   1.0.3
pooch                     1.7.0
portalocker               2.8.2
protobuf                  3.20.3
psutil                    5.9.8
py-cpuinfo                9.0.0
pycollada                 0.7.2
pycparser                 2.21
pydantic                  2.5.3
pydantic_core             2.14.6
pygit2                    1.14.1
pygltflib                 1.16.2
Pygments                  2.17.2
pyhocon                   0.3.60
PyMatting                 1.1.10
PyMCubes                  0.1.4
pymeshlab                 2023.12.post1
pyparsing                 3.1.1
pyproject-metadata        0.7.1
pyreadline3               3.4.1
python-dateutil           2.8.2
pytorch-lightning         2.1.0
pytorch-msssim            1.0.0
pytz                      2023.3.post1
PyWavelets                1.4.1
pywin32                   306
PyYAML                    6.0.1
qudida                    0.0.4
referencing               0.32.0
regex                     2023.8.8
rembg                     2.0.50
reportlab                 4.0.5
requests                  2.31.0
rich                      13.7.1
roma                      1.4.4
rpds-py                   0.16.2
Rtree                     1.1.0
safetensors               0.4.2
scikit-build              0.17.6
scikit_build_core         0.5.1
scikit-image              0.20.0
scikit-learn              1.3.1
scipy                     1.12.0
seaborn                   0.12.2
segment-anything          1.0
sentencepiece             0.1.99
setuptools                68.2.2
shapely                   2.0.2
simpleeval                0.9.13
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.0
sounddevice               0.4.6
svg.path                  6.3
svglib                    1.5.1
sympy                     1.12
tabulate                  0.9.0
tb-nightly                2.17.0a20240302
tensorboard-data-server   0.7.2
termcolor                 2.3.0
threadpoolctl             3.2.0
tifffile                  2023.9.18
timm                      0.6.13
tinycss2                  1.2.1
tokenizers                0.15.0
tomli                     2.0.1
torch                     2.2.1+cu118
torchaudio                2.2.1+cu118
torchmetrics              1.2.0
torchsde                  0.2.6
torchtyping               0.1.4
torchvision               0.17.1+cu118
tqdm                      4.66.2
trampoline                0.1.2
transformers              4.39.1
trimesh                   4.0.8
typeguard                 2.13.3
typing_extensions         4.10.0
typing-inspect            0.9.0
tzdata                    2023.3
ultralytics               8.0.183
urllib3                   1.26.18
varname                   0.13.0
wcwidth                   0.2.6
webencodings              0.5.1
websockets                11.0.3
Werkzeug                  3.0.1
wheel                     0.41.2
wrapt                     1.16.0
xatlas                    0.0.9
xformers                  0.0.25+cu118
xxhash                    3.4.1
yacs                      0.1.8
yapf                      0.40.1
yarl                      1.9.2
zipp                      3.17.0
</details>

**Comment by OracleToes** [comment]
Same problem :(

**Comment by pythongosssss** [comment]
This should now be fixed

**Comment by EvgeneKuklin** [comment]
Confirmed, it's working now, thank you

**Comment by afanfan98** [comment]
But how to solve the problem of slow response, it takes about 15 seconds, can you specify the TAG model?
