### ISSUE TITLE
error after the latest comfyui update

### ISSUE THREAD

**Issue by memedoggo** [pythongosssss/ComfyUI-WD14-Tagger#76]
```
Error handling request
Traceback (most recent call last):
  File "D:\ComfyUI\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\server.py", line 45, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\server.py", line 57, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\wd14tagger.py", line 165, in get_tags
    model = default if default in models else models[0]
                                              ~~~~~~^^^
IndexError: list index out of range

```

when I right-clicked context menu to use WD14 nothing happened and the console gave those messages

**Comment by liancheng-zcy** [comment]
+1

**Comment by liancheng-zcy** [comment]
no models

**Comment by chenrushun** [comment]
出错

**Comment by chenrushun** [comment]
更新后会崩，有同样的没

**Comment by albertpb** [comment]
this is old but, You can download the model through the node. Just use the node WD Tagger and it should download the model.
