### ISSUE TITLE
 CUDA_PATH is set but CUDA wasn't able to be loaded

### ISSUE THREAD

**Issue by ZeroCool22** [pythongosssss/ComfyUI-WD14-Tagger#86]
![Screenshot_11](https://github.com/user-attachments/assets/c02fd0e9-9f0c-4f29-8f87-661f142d547d)

![Screenshot_10](https://github.com/user-attachments/assets/95ad9be1-acc1-4d6a-abf9-461a8adaecd9)

![Screenshot_12](https://github.com/user-attachments/assets/9de0d936-2a48-415c-b032-3f288a5a7970)

```

C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-28 04:33:21.353791
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI
** Log path: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   1.9 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16376 MB, total RAM 32680 MB
pytorch version: 2.4.1+cu124
xformers version: 0.0.28.dev887
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\web
Adding extra search path checkpoints F:/Stable-diffusion
Adding extra search path configs path/to/stable-diffusion-webui/models/Stable-diffusion
Adding extra search path vae C:/Users/ZeroCool22/Desktop/AutoSDXL/stable-diffusion-webui/models/VAE
Adding extra search path loras C:/Users/ZeroCool22/Desktop/AutoSDXL/stable-diffusion-webui/models/Lora/Flux
Adding extra search path loras path/to/stable-diffusion-webui/models/LyCORIS
Adding extra search path upscale_models C:/Users/ZeroCool22/Desktop/AutoSDXL/stable-diffusion-webui/models/ESRGAN
Adding extra search path upscale_models path/to/stable-diffusion-webui/models/RealESRGAN
Adding extra search path upscale_models path/to/stable-diffusion-webui/models/SwinIR
Adding extra search path embeddings path/to/stable-diffusion-webui/embeddings
Adding extra search path hypernetworks path/to/stable-diffusion-webui/models/hypernetworks
Adding extra search path controlnet C:/Users/ZeroCool22/Desktop/AutoSDXL/stable-diffusion-webui/models/ControlNet/Flux
Adding extra search path clip C:/Users/ZeroCool22/Desktop/webui_forge/webui/models/text_encoder
C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
[Crystools INFO] Crystools version: 1.18.4
[Crystools INFO] CPU: AMD Ryzen 9 5900X 12-Core Processor - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4070 Ti SUPER
[Crystools INFO] NVIDIA Driver: 560.81
[ComfyUI-Easy-Use] server: v1.2.3 Loaded
[ComfyUI-Easy-Use] web root: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
Total VRAM 16376 MB, total RAM 32680 MB
pytorch version: 2.4.1+cu124
xformers version: 0.0.28.dev887
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
Unable to import guidedFilter, make sure you have only opencv-contrib-python or run the import_error_install.bat script
### Loading: ComfyUI-Impact-Pack (V7.8)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.7)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V2.51.2)
### ComfyUI Revision: 2732 [87331915] | Released on '2024-09-27'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
json_repair## OK
--------------
 ### Mixlab Nodes: Loaded
ChatGPT.available True
edit_mask.available True
## clip_interrogator_model not found: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\models\clip_interrogator\Salesforce\blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
ClipInterrogator.available True
## text_generator_model not found: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\models\prompt_generator\text2image-prompt-generator, pls download from https://huggingface.co/succinctly/text2image-prompt-generator/tree/main
## zh_en_model not found: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\models\prompt_generator\opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
TripoSR.available
MiniCPMNode.available
Scenedetect.available
FishSpeech.available
 --------------
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
[ReActor] - STATUS - Running v0.5.1-b2 in ComfyUI
Torch version: 2.4.1+cu124
C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable
############################################
C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\custom_nodes\ComfyUI-NAI-styler\CSV
############################################
[]
############################################
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
LOADED 6 FONTS
No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'


███╗   ███╗ █████╗  ██████╗██╗  ██╗██╗███╗   ██╗███████╗
████╗ ████║██╔══██╗██╔════╝██║  ██║██║████╗  ██║██╔════╝
██╔████╔██║███████║██║     ███████║██║██╔██╗ ██║█████╗
██║╚██╔╝██║██╔══██║██║     ██╔══██║██║██║╚██╗██║██╔══╝
██║ ╚═╝ ██║██║  ██║╚██████╗██║  ██║██║██║ ╚████║███████╗
╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝╚══════╝

██████╗ ███████╗██╗     ██╗   ██╗███████╗██╗ ██████╗ ███╗   ██╗███████╗
██╔══██╗██╔════╝██║     ██║   ██║██╔════╝██║██╔═══██╗████╗  ██║██╔════╝
██║  ██║█████╗  ██║     ██║   ██║███████╗██║██║   ██║██╔██╗ ██║███████╗
██║  ██║██╔══╝  ██║     ██║   ██║╚════██║██║██║   ██║██║╚██╗██║╚════██║
██████╔╝███████╗███████╗╚██████╔╝███████║██║╚██████╔╝██║ ╚████║███████║
╚═════╝ ╚══════╝╚══════╝ ╚═════╝ ╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝



# 😺dzNodes: LayerStyle -> Cannot import name 'guidedFilter' from 'cv2.ximgproc'
A few nodes cannot works properly, while most nodes are not affected. Please REINSTALL package 'opencv-contrib-python'.
For detail refer to https://github.com/chflame163/ComfyUI_LayerStyle/issues/5
[comfy_mtb] | INFO -> loaded 86 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
Initializing ControlAltAI Nodes

[rgthree-comfy] Loaded 42 exciting nodes. 🎉

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 218 nodes successfully.

        "The secret to getting ahead is getting started." - Mark Twain


Import times for custom nodes:
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-NAI-styler
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-mxToolkit
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inpaint-CropAndStitch
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Universal-Styler
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-lama-remover
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Miaoshouai-Tagger
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ControlAltAI-Nodes
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_JPS-Nodes
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\DJZ-Nodes
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-plasma
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\virtuoso-nodes
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Chibi-Nodes
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\aegisflow_utility_nodes
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\CharacterFaceSwap
   0.1 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-tensorops
   0.1 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light
   0.1 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
   0.1 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SAM2
   0.1 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle
   0.1 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.1 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.2 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.2 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-propost
   0.2 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2
   0.2 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-various
   0.3 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
   0.3 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR
   0.4 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.4 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.5 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.6 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fill-Nodes
   0.7 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Filters
   0.9 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspyrenet-Rembg
   1.0 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes
   1.5 seconds: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe-lightbox.esm.min.js
C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/pickr.min.js
C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe.min.css
FETCH DATA from: C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/classic.min.css
C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js
C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css
C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/model-viewer.min.js
QualityOfLifeSuit_Omar92::NSP ready
[comfy_mtb] | INFO -> Found multiple match, we will pick the last path/to/stable-diffusion-webui/models/SwinIR
['C:\\Users\\ZeroCool22\\Desktop\\ComfyUI_windows_portable\\ComfyUI\\models\\upscale_models', 'C:/Users/ZeroCool22/Desktop/AutoSDXL/stable-diffusion-webui/models/ESRGAN', 'path/to/stable-diffusion-webui/models/RealESRGAN', 'path/to/stable-diffusion-webui/models/SwinIR']
[comfy_mtb] | WARNING -> Face restoration models not found.
[]
[]
[]
[]
got prompt
2024-09-28 04:33:48.0652138 [E:onnxruntime:Default, provider_bridge_ort.cc:1351 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:636 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
2024-09-28 04:33:48.2125155 [E:onnxruntime:Default, provider_bridge_ort.cc:1351 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

!!! Exception during processing !!! D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:636 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

Traceback (most recent call last):
  File "C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:636 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\wd14tagger.py", line 200, in tag
    tags.append(wait_for_async(lambda: tag(image, model, threshold, character_threshold, exclude_tags, replace_underscore, trailing_comma)))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\pysssss.py", line 214, in wait_for_async
    loop.run_until_complete(run_async())
  File "asyncio\base_events.py", line 654, in run_until_complete
  File "C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\pysssss.py", line 204, in run_async
    r = await async_fn()
        ^^^^^^^^^^^^^^^^
  File "C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\wd14tagger.py", line 58, in tag
    model = InferenceSession(name, providers=defaults["ortProviders"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 394, in __init__
    raise fallback_error from e
  File "C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 389, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "C:\Users\ZeroCool22\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:636 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.


Prompt executed in 0.42 seconds
```

**Comment by ZeroCool22** [comment]
![Screenshot_13](https://github.com/user-attachments/assets/f0b25778-7098-4e59-9e80-51db545b1347)

**Comment by sxcbing** [comment]
同样报错，问题解决了吗

**Comment by ZeroCool22** [comment]
> 同样报错，问题解决了吗

Yes, do this:

go to ComfyUI_windows_portable\python_embeded,
type CMD in addressbar, hit enter:
paste python.exe -s -m pip uninstall onnxruntime
type yes(Y)
PASTE python.exe -s -m pip uninstall onnxruntime-gpu
type yes(Y)
run comfyui
go to Manager - Install missing custom nodes - click 'Try to fix it' button
Restart
