### ISSUE TITLE
[Program crashes with exit code 3221226505 (0xC0000409)] Here is an analysis of the exit code. This may not be accurate, please refer to it as appropriate! System exit code name: STACK_BUFFER_OVERRUN

### ISSUE THREAD

**Issue by mujiu612** [pythongosssss/ComfyUI-WD14-Tagger#93]
Starting server

To see the GUI go to: http://127.0.0.1:8188
C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe-lightbox.esm.min.js
C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe.min.css
FETCH DATA from: C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\custom_nodes\comfyui-mixlab-nodes\webApp\lib/pickr.min.js
C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\custom_nodes\comfyui-mixlab-nodes\webApp\lib/classic.min.css
C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\custom_nodes\comfyui-mixlab-nodes\webApp\lib/model-viewer.min.js
C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css
C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js
got prompt
!!! Exception during processing !!! [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-WD14-Tagger\models\wd-v1-4-moat-tagger-v2.onnx failed:Load model C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-WD14-Tagger\models\wd-v1-4-moat-tagger-v2.onnx failed. File doesn't exist
Traceback (most recent call last):
  File "C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-WD14-Tagger\wd14tagger.py", line 200, in tag
    tags.append(wait_for_async(lambda: tag(image, model, threshold, character_threshold, exclude_tags, replace_underscore, trailing_comma)))
  File "C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-WD14-Tagger\pysssss.py", line 207, in wait_for_async
    return asyncio.run(async_fn())
  File "C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\python\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-WD14-Tagger\wd14tagger.py", line 58, in tag
    model = InferenceSession(name, providers=defaults["ortProviders"])
  File "C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 480, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-WD14-Tagger\models\wd-v1-4-moat-tagger-v2.onnx failed:Load model C:\RJ\B-ComfyUI\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-WD14-Tagger\models\wd-v1-4-moat-tagger-v2.onnx failed. File doesn't exist

Prompt executed in 0.15 seconds
got prompt
Could not locate cudnn_graph64_9.dll. Please make sure it is in your library path!
Invalid handle. Cannot load symbol cudnnCreate

--------
[程序崩溃，退出代码为 3221226505 (0xC0000409)]
以下是对退出代码的分析。这可能不准确，请酌情参考！
系统退出代码名称: STACK_BUFFER_OVERRUN
系统退出代码描述: 系统在此应用程序中检测到基于堆栈的缓冲区溢出。溢出可能允许恶意用户获得此应用程序的控制。
请注意，通常退出代码与其描述都不足以诊断问题！
总是上传完整日志而非只有退出代码。

Does anyone have this problem? I tried a lot of things but it didn't work out.

**Comment by cxx1985121** [comment]
我也是这个问题

**Comment by w3c0929** [comment]
同样是这个问题

**Comment by liaceboy** [comment]
同样是这个问题

**Comment by TEQUILA02** [comment]
This problem occurs because your computer lacks “cuda and cudnn”, the specific solution to the answer, please look for “cuda and cudnn” related environment configuration tutorials on the net!

**Comment by baicai99** [comment]
same

**Comment by WILLTOM64** [comment]
me too

**Comment by WILLTOM64** [comment]
update to Torch 2.5.1 (CUDA 12.4)xFormers 0.0.28.post3

**Comment by yangzi0802** [comment]
me toooooooo~

**Comment by genifycom** [comment]
Same

The ComfyUI process exited (exit code 3221226505). You can restart it below. See the logs for details.
